#!/usr/bin/env python3
"""Generate reference QR code matrices for testing QR.Encode in Dyalog APL.

Usage:
    pip install segno
    python generate_test_references.py

This produces one text file per test case in test_references/.
Each file contains one row per line; each row is a string of '0' and '1' characters
representing the QR code module matrix (no quiet zone).

The APL test script (test_qr.apls) reads these files and compares them
against the output of QR.Encode.
"""

import os
import segno

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_references")

# ─── Test cases ───────────────────────────────────────────────────────────────
# Each entry: (filename, data, error, version, mask, mode)
# mask=None means auto mask selection
# mode: 'numeric', 'alphanumeric', 'byte'
TEST_CASES = [
    ("tc01_alpha_Q_mask0.txt",    "HELLO WORLD",          "Q", 1, 0, "alphanumeric"),
    ("tc02_alpha_H_mask3.txt",    "HELLO WORLD",          "H", 2, 3, "alphanumeric"),
    ("tc03_num_M_mask2.txt",      "01234567",             "M", 1, 2, "numeric"),
    ("tc04_byte_L_mask5.txt",     "Hello, world!",        "L", 1, 5, "byte"),
    ("tc05_alpha_H_mask7.txt",    "AC-42",                "H", 1, 7, "alphanumeric"),
    ("tc06_byte_M_mask1.txt",     "https://example.com",  "M", 2, 1, "byte"),
    ("tc07_num_Q_mask4.txt",      "0123456789012345",     "Q", 1, 4, "numeric"),
    ("tc08_alpha_M_auto.txt",     "HELLO WORLD",          "M", 1, None, "alphanumeric"),
    ("tc09_num_H_auto.txt",       "1234567890",           "H", 1, None, "numeric"),
    ("tc10_byte_L_mask6.txt",     "Test1234!",            "L", 1, 6, "byte"),
]


def generate_reference(data, error, version, mask, mode):
    """Generate a QR code matrix using segno and return as list of row strings."""
    kwargs = dict(
        error=error,
        version=version,
        boost_error=False,
        micro=False,
        mode=mode,
    )
    if mask is not None:
        kwargs["mask"] = mask

    qr = segno.make(data, **kwargs)

    # Verify no quiet zone is included in matrix
    expected_size = 17 + 4 * version
    matrix = qr.matrix
    assert len(matrix) == expected_size, \
        f"Expected {expected_size}x{expected_size}, got {len(matrix)}x{len(matrix[0])}"
    assert len(matrix[0]) == expected_size

    rows = ["".join(str(cell) for cell in row) for row in matrix]
    return rows, qr.mask


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print(f"Generating {len(TEST_CASES)} reference QR matrices in {OUTPUT_DIR}/")
    print()

    for filename, data, error, version, mask, mode in TEST_CASES:
        filepath = os.path.join(OUTPUT_DIR, filename)
        rows, actual_mask = generate_reference(data, error, version, mask, mode)

        with open(filepath, "w", encoding="utf-8", newline="\n") as f:
            for row in rows:
                f.write(row + "\n")

        mask_desc = f"mask {mask}" if mask is not None else f"auto (chose {actual_mask})"
        print(f"  {filename:35s}  {len(rows)}x{len(rows[0])}  {mask_desc}")

    # Write a manifest for documentation
    manifest_path = os.path.join(OUTPUT_DIR, "README.md")
    with open(manifest_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# QR Test Reference Files\n\n")
        f.write("Generated by `generate_test_references.py` using the `segno` Python library.\n\n")
        f.write("## Regeneration\n\n")
        f.write("```bash\n")
        f.write("pip install segno\n")
        f.write("python generate_test_references.py\n")
        f.write("```\n\n")
        f.write("## Test Cases\n\n")
        f.write("| File | Data | EC | Version | Mask | Mode |\n")
        f.write("|------|------|----|---------|------|------|\n")
        for filename, data, error, version, mask, mode in TEST_CASES:
            mask_str = str(mask) if mask is not None else "auto"
            f.write(f"| {filename} | `{data}` | {error} | {version} | {mask_str} | {mode} |\n")
        f.write("\n## File Format\n\n")
        f.write("Each `.txt` file contains the QR module matrix (no quiet zone).\n")
        f.write("One row per line; each character is `0` (white) or `1` (black).\n")
        f.write("Parse in APL: `ref ← '1'=↑⊃⎕NGET filename 1`\n")

    print()
    print("Done. Reference files and README.md written.")


if __name__ == "__main__":
    main()
